# Generated by Django 5.2.5 on 2025-08-14 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du drone')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('drone_type', models.CharField(choices=[('quadcopter', 'Quadricoptère'), ('hexacopter', 'Hexacoptère'), ('octocopter', 'Octocoptère'), ('fixed_wing', 'Aile fixe'), ('helicopter', 'Hélicoptère'), ('other', 'Autre')], max_length=20, verbose_name='Type de drone')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de série')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids (kg)')),
                ('max_payload', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Charge utile max (kg)')),
                ('max_flight_time', models.IntegerField(blank=True, null=True, verbose_name='Temps de vol max (minutes)')),
                ('max_range', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Portée max (km)')),
                ('max_altitude', models.IntegerField(blank=True, null=True, verbose_name='Altitude max (m)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('maintenance', 'En maintenance'), ('inactive', 'Inactif'), ('retired', 'Retiré')], default='active', max_length=20, verbose_name='Statut')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'enregistrement")),
                ('insurance_info', models.TextField(blank=True, verbose_name="Informations d'assurance")),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='Notes de maintenance')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Dernière maintenance')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Prochaine maintenance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drones/', verbose_name='Photo du drone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
                'db_table': 'drone',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneFlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_date', models.DateTimeField(verbose_name='Date et heure de vol')),
                ('duration', models.IntegerField(verbose_name='Durée du vol (minutes)')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu de vol')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='Objectif du vol')),
                ('weather_conditions', models.TextField(blank=True, verbose_name='Conditions météo')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de vol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='authentication.drone', verbose_name='Drone')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloted_flights', to=settings.AUTH_USER_MODEL, verbose_name='Pilote')),
            ],
            options={
                'verbose_name': 'Vol de drone',
                'verbose_name_plural': 'Vols de drones',
                'db_table': 'drone_flight',
                'ordering': ['-flight_date'],
            },
        ),
    ]
