# Generated by Django 5.2.5 on 2025-08-15 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airport_id', models.CharField(max_length=10, unique=True, verbose_name='Identifiant unique')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'aéroport/aérodrome")),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Code IATA/ICAO')),
                ('airport_type', models.CharField(choices=[('international', 'Aéroport International'), ('domestic', 'Aéroport Domestique'), ('aerodrome', 'Aérodrome')], max_length=20, verbose_name='Type')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Aéroport/Aérodrome',
                'verbose_name_plural': 'Aéroports/Aérodromes',
                'db_table': 'airport',
                'ordering': ['airport_type', 'city', 'name'],
                'indexes': [models.Index(fields=['airport_type'], name='airport_airport_5713cd_idx'), models.Index(fields=['city'], name='airport_city_3b5087_idx'), models.Index(fields=['is_active'], name='airport_is_acti_700601_idx')],
            },
        ),
    ]
