# Generated by Django 5.2.5 on 2025-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Rayon de la zone interdite (km)'),
        ),
    ]
