# Generated by Django 5.2.5 on 2025-08-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_airport_radius'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['airport_type', 'name'], 'verbose_name': 'Aéroport/Aérodrome', 'verbose_name_plural': 'Aéroports/Aérodromes'},
        ),
        migrations.RemoveIndex(
            model_name='airport',
            name='airport_is_acti_700601_idx',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_id',
            field=models.CharField(max_length=10, unique=True, verbose_name="Identifiant unique de l'aéroport"),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_type',
            field=models.CharField(choices=[('international', 'Aéroport International'), ('domestic', 'Aéroport Domestique'), ('aerodrome', 'Aérodrome')], max_length=20, verbose_name="Type d'aéroport"),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code IATA'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'aéroport"),
        ),
        migrations.AlterField(
            model_name='airport',
            name='radius',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rayon de la zone interdite (km)'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['latitude', 'longitude'], name='airport_latitud_204988_idx'),
        ),
    ]
