# Generated by Django 5.2.5 on 2025-08-16 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_airport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalPark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('park_id', models.CharField(max_length=20, unique=True, verbose_name='Identifiant unique du parc')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du parc')),
                ('type', models.CharField(default='national_park', max_length=50, verbose_name='Type de zone')),
                ('area', models.CharField(max_length=50, verbose_name='Superficie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Parc national',
                'verbose_name_plural': 'Parcs nationaux',
                'db_table': 'national_park',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NaturalReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserve_id', models.CharField(max_length=20, unique=True, verbose_name='Identifiant unique de la réserve')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la réserve')),
                ('type', models.CharField(default='natural_reserve', max_length=50, verbose_name='Type de zone')),
                ('area', models.CharField(max_length=50, verbose_name='Superficie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Réserve naturelle',
                'verbose_name_plural': 'Réserves naturelles',
                'db_table': 'natural_reserve',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedAreaCoordinates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre des coordonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('national_park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='authentication.nationalpark')),
                ('natural_reserve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='authentication.naturalreserve')),
            ],
            options={
                'verbose_name': 'Coordonnées de zone protégée',
                'verbose_name_plural': 'Coordonnées des zones protégées',
                'db_table': 'protected_area_coordinates',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['natural_reserve', 'order'], name='protected_a_natural_7cacb7_idx'), models.Index(fields=['national_park', 'order'], name='protected_a_nationa_ffeba7_idx')],
            },
        ),
    ]
