# Generated by Django 5.2.5 on 2025-08-16 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_nationalpark_naturalreserve_protectedareacoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='airport',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name="Approuvé par l'admin"),
        ),
        migrations.AddField(
            model_name='nationalpark',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='nationalpark',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name="Approuvé par l'admin"),
        ),
        migrations.AddField(
            model_name='naturalreserve',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='naturalreserve',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name="Approuvé par l'admin"),
        ),
        migrations.AddField(
            model_name='protectedareacoordinates',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='protectedareacoordinates',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name="Approuvé par l'admin"),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['is_active'], name='airport_is_acti_700601_idx'),
        ),
        migrations.AddIndex(
            model_name='nationalpark',
            index=models.Index(fields=['is_active'], name='national_pa_is_acti_cc7c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='naturalreserve',
            index=models.Index(fields=['is_active'], name='natural_res_is_acti_c1c556_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedareacoordinates',
            index=models.Index(fields=['is_active'], name='protected_a_is_acti_5d21bb_idx'),
        ),
    ]
