# Generated by Django 5.2.5 on 2025-08-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_airport_created_by_airport_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalpark',
            name='coordinates',
            field=models.JSONField(default=1, help_text='Liste de coordonnées [lat, lng]', verbose_name='Coordonnées GPS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalreserve',
            name='coordinates',
            field=models.JSONField(default=1, help_text='Liste de coordonnées [lat, lng]', verbose_name='Coordonnées GPS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protectedareacoordinates',
            name='national_park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_coordinates', to='authentication.nationalpark'),
        ),
        migrations.AlterField(
            model_name='protectedareacoordinates',
            name='natural_reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_coordinates', to='authentication.naturalreserve'),
        ),
    ]
