# Generated by Django 5.2.5

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_nationalpark_coordinates_naturalreserve_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTBlacklistedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True, verbose_name='Token JWT blacklisté')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de blacklist')),
                ('expires_at', models.DateTimeField(verbose_name='Date d\'expiration')),
                ('user_id', models.UUIDField(verbose_name='ID de l\'utilisateur')),
                ('token_type', models.CharField(choices=[('access', 'Token d\'accès'), ('refresh', 'Token de rafraîchissement')], max_length=10, verbose_name='Type de token')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Raison du blacklist')),
            ],
            options={
                'verbose_name': 'Token JWT blacklisté',
                'verbose_name_plural': 'Tokens JWT blacklistés',
                'db_table': 'jwt_blacklisted_token',
                'ordering': ['-blacklisted_at'],
                'indexes': [
                    models.Index(fields=['user_id'], name='jwt_blackli_user_id_idx'),
                    models.Index(fields=['token_type'], name='jwt_blackli_token_ty_idx'),
                    models.Index(fields=['expires_at'], name='jwt_blackli_expires_idx'),
                ],
            },
        ),
    ]
